# Use a base image with yum support
FROM amazonlinux:latest

# Update the system and install Apache
RUN yum update -y && \
    yum install -y httpd && \
    

# Set the working directory
WORKDIR /var/www/html

# Copy the custom index.html to the Apache document root
COPY index.html /var/www/html/

# Expose port 80
EXPOSE 80

# Set the entrypoint to run Apache in the foreground
ENTRYPOINT ["/usr/sbin/httpd", "-D", "FOREGROUND"]